version: '3.1'
services:

  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    image: n0r1sk-tomcat:latest
    ports:
      - "11111:8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: n0r1sk-nginx:latest
    ports:
      - "80:80"
      - "443:443"
